name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ['master']
  workflow_dispatch:
 
jobs:
  buildImage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'gary002' 
          # Container registry password
          password: 'HZmTzSWIgX9Aies1Ia0Cizu2lqseKmRB8ummCVTKT6+ACRCG5sUd'
          # Container registry server url
          login-server: 'gary002.azurecr.io'
    
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: gary002.azurecr.io/hello-world-app:${{github.sha}}
          file: ./Dockerfile
      
  deployToAKS:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello"
